name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake, Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.21.0"
          ninjaVersion: "1.10.2"

      - name: Configure CMake
        # Note: No need to specify compilers for CMake. Let CMake auto-detect the compiler.
        run: |
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}
        shell: bash

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
        shell: bash

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --build-config ${{ matrix.build_type }}
        shell: bash
